### ISSUE TITLE
Channel placeholder for discord to minecraft

### ISSUE THREAD

**Issue by SaitDev** [Scarsz/DiscordSRV#317] opened 2018-03-02 14:45 UTC
Please parse ingame channel's placeholder on setting `DiscordToMinecraftChatMessageFormat` if avaible instead of only `ChatChannelHookMessageFormat`

Reason: `%channelcolor%` on `ChatChannelHookMessageFormat` will be useless if we have some color on `DiscordToMinecraftChatMessageFormat` too

**Comment by Scarsz** [comment] 2018-03-02 15:16
I don't get what your reasoning behind this is

**Comment by SaitDev** [comment] 2018-03-02 15:42
sorry for not clear enough.
discordsrv have placeholer to help message has same color as ingame chat: `ChatChannelHookMessageFormat: "%channelcolor%%message%"`

but if we r also using `%toprolecolor%` : `DiscordToMinecraftChatMessageFormat: %toprolecolor%%username% » %message%` 

the final message discordsrv parsing will be: `%channelcolor%%toprolecolor%%username% » %message%`
which mean `%channelcolor%` cant effect **%message%** but `%toprolecolor%` does

**Comment by Scarsz** [comment] 2018-03-13 01:18
Not possible due to the way code flows in the current version of DiscordSRV, potentially a fix for this with v2

**Comment by Scarsz** [comment] 2018-03-13 01:45
Duplicate of #254

**Closed by Scarsz** 2018-03-13 01:45 UTC
Labels: duplicate
