### ISSUE TITLE
Sponge? 

### ISSUE THREAD

**Issue by DFameYT** [Scarsz/DiscordSRV#311] opened 2018-02-12 13:34 UTC
Will this Plugin work on sponge/forge servers

**Comment by merjilin** [comment] 2018-02-12 14:23
Not yet, no. DiscordSRV2 is in the works which will support Spigot, bungee, forge and sponge.

**Comment by VankkaGithub** [comment] 2018-02-12 15:15
@merjilin Forge support was dropped https://github.com/Scarsz/DiscordSRV2/commit/a7f84535fb289ffddabd661774441eb45e3ee85c

**Comment by DFameYT** [comment] 2018-02-12 15:32
What about sponge

**Comment by VankkaGithub** [comment] 2018-02-12 15:32
that's going to be in DiscordSRV2

**Comment by Eufranio** [comment] 2018-02-12 15:34
For now: https://github.com/Eufranio/MagiBridge

**Comment by VankkaGithub** [comment] 2018-02-12 15:38
Dupe of https://github.com/Scarsz/DiscordSRV/issues/30

**Comment by DFameYT** [comment] 2018-02-12 17:10
Looking forward to the DiscordSRV2? Any idea of a release date

**Comment by VankkaGithub** [comment] 2018-02-12 17:12
some day. no eta really

**Comment by Scarsz** [comment] 2018-02-12 19:36
There is no ETA for DiscordSRV2.

**Closed by Scarsz** 2018-02-12 19:36 UTC
