### ISSUE TITLE
Set Discord nickname as in game nickname

### ISSUE THREAD

**Issue by Turbotailz** [Scarsz/DiscordSRV#289] opened 2018-01-04 13:06 UTC
Can you add an option that allows us to set **MinecraftDiscordAccountLinkedSetDiscordNicknameAsInGameName** as their display name instead of the IGN? Many players on my server prefer their nicknames and are unlinking their accounts just so they can have their desired Discord name again (I tell them to just change their IGN but they're stubborn).

**Comment by Scarsz** [comment] 2018-03-13 01:50
Duplicate of #227

**Closed by Scarsz** 2018-03-13 01:50 UTC
