### ISSUE TITLE
High cpu usage channel topic updater

### ISSUE THREAD

**Issue by popcorn9499** [Scarsz/DiscordSRV#115] opened 2017-02-18 03:09 UTC
I am having a issue with high cpu usage with your plugin. It seems to be related to one class [link](https://github.com/Scarsz/DiscordSRV/blob/master/src/main/java/com/scarsz/discordsrv/threads/ChannelTopicUpdater.java)

I dont know java that well but from when i was reading the visualvm profiling i saw this class have all the tick look. I disabled the channel topic updater rate by doing -1 and it seemed to negate the issue but i still feel like this is a bug since that was alot of cpu for updating every 5 seconds. I am unsure what exactly you would like me to do but ill help test this. 

versions

Spigot 1.11
discordsrv 12.4

I hope this helps please mention anything if you find anything new on this

**Comment by popcorn9499** [comment] 2017-02-18 03:11
forgot to add this. its the profiling of the cpu [link](https://i.imgur.com/PdD9P2K.png) its just a screenshot

**Comment by Scarsz** [comment] 2017-02-18 03:19
`I disabled the channel topic updater rate by doing -1`
That is **_not_** how you disable the channel topic updater. You've probably put it into a loop where the topics are constantly updating.

**Comment by popcorn9499** [comment] 2017-02-18 15:05
how would i go about disabling it then because not doing that your plugin used all of one core. by creating that loop it used like 2% of a core. If it was in a loop would it of not used more? just asking. I did -1 because thats how most mod/plugin devs disable stuff. Now i would like to understand the underlying issue not how i incorrectly disabled the changing topics

**Comment by Scarsz** [comment] 2017-02-18 18:18
To disable it you change the topic messages to blank, as the instructions
directly above the config options state. This issue isn't reproducible.

**Comment by popcorn9499** [comment] 2017-02-18 19:02
The topic messages thing was blank and it didn't help even

**Comment by Scarsz** [comment] 2017-02-18 20:33
If the topic message formats were blank the thread wouldn't be activate at all. Closing because I can't reproduce this.

**Closed by Scarsz** 2017-02-18 20:33 UTC
Labels: bug, cant-reproduce, invalid
